services:
  - type: web
    name: insight-invest-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: "."
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: API_KEY
        sync: false

  - type: web
    name: insight-invest-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/dashboard/app.py
    envVars:
      - key: PYTHONPATH
        value: "."
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
